# Generated by Django 5.1.2 on 2024-12-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyClinic', '0004_doctorappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='appointment',
        ),
    ]
